/**
 * generate.test.ts — regenerates the committed golden-controls snapshots from the portal SIM.
 *
 * SKIPPED by default. Run explicitly, with a real local Chromium available (app/ or
 * legacy/automation/ node_modules), to (re)produce worker/test/golden/<category>.json and the
 * runtime barrel worker/src/golden-controls.ts:
 *
 *     cd worker && GEN_GOLDENS=1 npx vitest run test/golden/generate.test.ts
 *
 * It drives the REAL driver's in-page collector (`collectStep3Controls` from src/portal.ts) against
 * the Power-Pages-shaped mock (test/sim/server.ts), so the goldens match what the live
 * `dumpControls()` produces, normalized by src/drift.ts. When Rob files real reports, alice replaces
 * a `"source": "sim"` golden with a live dump (`"source": "live"`) — see docs/engine-sync.md.
 */
import { describe, it, beforeAll, afterAll, expect, vi } from 'vitest';
// portal.ts imports @cloudflare/playwright (pulls in cloudflare:workers, unresolvable under Node/vitest).
// We only need its pure `collectStep3Controls`; the real Chromium comes from ./sim/browser. Stub the module.
vi.mock('@cloudflare/playwright', () => ({ launch: async () => { throw new Error('generator uses launchLocalChromium, not @cloudflare/playwright'); } }));
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { startSim, type Sim } from '../sim/server';
import { launchLocalChromium } from '../sim/browser';
import { collectStep3Controls } from '../../src/portal';
import { normalizeControls, type GoldenSnapshot } from '../../src/drift';
import { CATEGORIES } from '../../../shared/categories.js';

const HERE = dirname(fileURLToPath(import.meta.url)); // worker/test/golden
const SRC_BARREL = resolve(HERE, '..', '..', 'src', 'golden-controls.ts');

/** Categories with a sim Step-3 fixture that we snapshot (the mapped launch set, per the task). */
const TARGETS = ['pothole', 'bins_carts', 'abandoned_vehicle', 'animal_control', 'noise'];

describe.runIf(process.env.GEN_GOLDENS === '1')('regenerate golden-controls snapshots (sim)', () => {
  let sim: Sim;
  let browser: any;

  beforeAll(async () => {
    sim = await startSim();
    browser = await launchLocalChromium();
  }, 60_000);

  afterAll(async () => {
    await browser?.close().catch(() => {});
    await sim?.close();
  });

  it('dumps each mapped category and writes JSON + the runtime barrel', async () => {
    const context = await browser.newContext();
    await context.addCookies([{ name: 'sim_auth', value: '1', url: sim.url }]);
    const page = await context.newPage();
    const capturedAt = new Date().toISOString();
    const snapshots: Record<string, GoldenSnapshot> = {};

    for (const category of TARGETS) {
      const cfg = CATEGORIES[category];
      if (!cfg) throw new Error(`unknown category ${category}`);

      // Create a draft session for this case type (Step 1 → Step 2), then resume Step 3 and dump.
      await page.goto(`${sim.url}/my-requests/New-Request/`, { waitUntil: 'domcontentloaded' });
      await page.evaluate((guid: string) => {
        (document.querySelector('#cop_casetype_guid') as any).value = guid;
        (document.querySelector('#casetypecode') as any).value = '2';
        (document.querySelector('#step1form') as any).submit();
      }, cfg.portalCaseTypeGuid);
      await page.waitForURL(/stepid=step2/, { timeout: 15_000 });
      const entityId = await page.$eval('#EntityFormView_EntityID', (el: any) => el.value);
      await page.goto(`${sim.url}/my-requests/New-Request/?stepid=step3&id=${entityId}`, { waitUntil: 'domcontentloaded' });
      await page.waitForSelector('#description', { timeout: 15_000 });

      const raw = await page.evaluate(collectStep3Controls);
      const controls = normalizeControls(raw);
      const snap: GoldenSnapshot = { category, caseTypeName: cfg.portalCaseTypeName, source: 'sim', capturedAt, controls };
      snapshots[category] = snap;
      writeFileSync(resolve(HERE, `${category}.json`), JSON.stringify(snap, null, 2) + '\n');
    }

    await context.close();

    // Runtime barrel: the Worker can't read files, so bundle the snapshots the engine diffs against.
    const barrel =
      `/**\n` +
      ` * golden-controls.ts — GENERATED by worker/test/golden/generate.test.ts. DO NOT EDIT BY HAND.\n` +
      ` * Runtime copy of worker/test/golden/*.json for the drift canary (Workers have no fs).\n` +
      ` * Regenerate: cd worker && GEN_GOLDENS=1 npx vitest run test/golden/generate.test.ts\n` +
      ` */\n` +
      `import type { GoldenSnapshot } from './drift.js';\n\n` +
      `export const GOLDEN_CONTROLS: Record<string, GoldenSnapshot> = ${JSON.stringify(snapshots, null, 2)};\n`;
    writeFileSync(SRC_BARREL, barrel);

    expect(Object.keys(snapshots).sort()).toEqual([...TARGETS].sort());
  }, 120_000);
});
