/**
 * golden-controls.ts — GENERATED by worker/test/golden/generate.test.ts. DO NOT EDIT BY HAND.
 * Runtime copy of worker/test/golden/*.json for the drift canary (Workers have no fs).
 * Regenerate: cd worker && GEN_GOLDENS=1 npx vitest run test/golden/generate.test.ts
 */
import type { GoldenSnapshot } from './drift.js';

export const GOLDEN_CONTROLS: Record<string, GoldenSnapshot> = {
  "pothole": {
    "category": "pothole",
    "caseTypeName": "Pothole Report",
    "source": "sim",
    "capturedAt": "2026-08-23T01:50:44.554Z",
    "controls": [
      {
        "id": "cop_size",
        "label": "Approximate size of the pothole",
        "kind": "select",
        "required": false,
        "options": [
          "Small (~4in)",
          "Medium (~28in)",
          "Large (~36in)",
          "Unknown"
        ]
      }
    ]
  },
  "bins_carts": {
    "category": "bins_carts",
    "caseTypeName": "Trash or Recycling Bins or Carts",
    "source": "sim",
    "capturedAt": "2026-08-23T01:50:44.554Z",
    "controls": [
      {
        "id": "cop_cartrequesttype",
        "label": "I",
        "kind": "radio",
        "required": false,
        "options": [
          "did not receive my new carts.",
          "My old carts were not removed",
          "Other"
        ]
      }
    ]
  },
  "abandoned_vehicle": {
    "category": "abandoned_vehicle",
    "caseTypeName": "Abandoned Vehicle to Report",
    "source": "sim",
    "capturedAt": "2026-08-23T01:50:44.554Z",
    "controls": [
      {
        "id": "cop_vehicledetails",
        "label": "Vehicle details (make, model, color, plate)",
        "kind": "text",
        "required": false
      }
    ]
  },
  "animal_control": {
    "category": "animal_control",
    "caseTypeName": "Animal Control Concerns",
    "source": "sim",
    "capturedAt": "2026-08-23T01:50:44.554Z",
    "controls": [
      {
        "id": "cop_typeofanimal",
        "label": "Type of animal",
        "kind": "select",
        "required": false,
        "options": [
          "Domestic",
          "Wildlife"
        ]
      }
    ]
  },
  "noise": {
    "category": "noise",
    "caseTypeName": "Noise or Sound Disturbances",
    "source": "sim",
    "capturedAt": "2026-08-23T01:50:44.554Z",
    "controls": [
      {
        "id": "cop_noisesource",
        "label": "Where is the noise coming from?",
        "kind": "select",
        "required": false,
        "options": [
          "Residence",
          "Business",
          "Street or Public Space",
          "Construction",
          "Other"
        ]
      }
    ]
  }
};
